### ISSUE TITLE
Специальные мнения  - иногда не находит

### ISSUE THREAD

**Issue by Rexarrior** [Rexarrior/ALT#13]
В некоторых документах не находит особые мнения. Пока сдедали заглушку - поиск до конца документов. Нужно разобраться, почему не находит. Исправить способ поиска, если необходимо. Заменить заглушку на постоянное решение.

**Comment by mehwhatever0** [comment]
Выполнено. Необходимо провести ревью https://github.com/Rexarrior/ALT/pull/26
Коммит https://github.com/Rexarrior/ALT/pull/26/commits/166d9332f3e207f1ec2c44cd02c1ef71fd0df2fd
