### ISSUE TITLE
Перезапись при получении заголовков

### ISSUE THREAD

**Issue by Rexarrior** [Rexarrior/ALT#16]
Необходимо исправить ситуацию с перезаписью заголовков при  их получении с сайта. В настоящий момент, если парсер встречает uid, для которого уже существует заголовок, то он перезаписывает старый заголовок новым. Нужно сделать так, чтобы для одного uid сохранялись несколько заголовков.

**Comment by mehwhatever0** [comment]
Сделано. Требуется ревью и возможные другие варианты. Текущая реализация в реквесте https://github.com/Rexarrior/ALT/pull/26: уникальные и не уникальные заголовки хранятся в одном словаре. Элементом для уникального ключа является словарь его параметров (дата, заголовок, ссылка), для неуникального — кортеж ('not unique', dict), где dict — список словарей аналогичных элементам уникальных ключей. При обработке словаря заголовков неуникальные ключи, а значит и их заголовки, отсекаются проверкой на вхождение литерала 'not unique':

if 'not unique' in headersDict: continue

Коммит https://github.com/Rexarrior/ALT/pull/26/commits/7d020984134491ef13395e554ef5ae640e1cff1e

#16 пересекается с #17
