### ISSUE TITLE
Ключ 'textfile' в заголовках

### ISSUE THREAD

**Issue by Rexarrior** [Rexarrior/ALT#20]
Добавить ключ textfile в заголовках, чтобы не перезаписывать uri исходного документа.

**Comment by mehwhatever0** [comment]
Выполнено. Необходимо провести ревью https://github.com/Rexarrior/ALT/pull/26
Коммит https://github.com/Rexarrior/ALT/pull/26/commits/e2393cbcc749e5aa835e1ab29caa835eaf1c8847
