### ISSUE TITLE
Переработать функцию GetResolutionHeaders

### ISSUE THREAD

**Issue by Rexarrior** [Rexarrior/ALT#22]
**В текущей реализации:
1. В конце цикла осуществляется переход на лишню страницу
2. Возможена ошибка из-за перехода на несуществующую страницу. 
Нужно реорганизовать метод, учтя тот факт, что при переходе на уже открытую страницу так же возникает ошибка.

**Comment by mehwhatever0** [comment]
Перешел на последнюю страницу при сборке всех заголовков. Ошибки не возникло.

**Comment by Rexarrior** [comment]
Закрыто за отсутствием описанных проблем.
