### ISSUE TITLE
Ссылка на несколько постановлений одного года

### ISSUE THREAD

**Issue by Rexarrior** [Rexarrior/ALT#37]
Существуют ссылки вида 

> определения от 23 июня 2005 года № 272-О, от 16 мая 2007 года № 420-О-О, № 421-О-О и № 422-О-О, от 17 июня 2008 года № 498-О-О"

Нужно как-то модифицировать алгоритм грубой выборки, чтоб такие ссылки корректно выделялись. 
Сейчас результат грубой выборки следующий:
 ['от 23 июня 2005 года № 272-О', 'от 16 мая 2007 года № 420-О-О', 'от 17 июня 2008 года № 498-О-О']

**Comment by mehwhatever0** [comment]
fixed
